### ISSUE TITLE
bulk RNAseq data

### ISSUE THREAD

**Issue by lishashali** [xzhoulab/iDEA#17]
Hi iDEA team,Thank you for the great package. Is this method applicable to bulk rnaseq fpkm data?

**Comment by YingMa0107** [comment]
Hi @lishashali,

Thanks for your interest in our package. This method is also applicable to bulk RNAseq fpkm data since our method is bulit on summary statistics. Acutally in our iDEA paper, we also have one application on bulk RNAseq data, please see details in the discussion part and supplementary materials (specifically, Supplementary Figure 30 and Supplementary Note 3) if you are interested.
