### ISSUE TITLE
Time to run extremely high

### ISSUE THREAD

**Issue by csjansen** [xzhoulab/iDEA#23]
I'm attempting to run your tutorial on a human dataset with a gene set of only ~3500 genes on a HPC.  This is with a new R installation and a new iDEA installation.  Any idea why I'm getting an ETA in the multiple days for iDEA.fit?  This is following your tutorial to the letter.
<img width="1724" alt="InsaneETA" src="https://user-images.githubusercontent.com/13241688/170048525-d2b38f86-f594-4764-b482-b01c32298839.png">

**Comment by YingMa0107** [comment]
Hi @csjansen, 

Thank you for your interest in our package! Could you please provide your sessionInfo() here? If you are using Windows system, the number of cores used will be forced to be 1 since Windows system does not support the mcapply (multi-core parallel computing) at the time when we developed the package. It should be able to use multi-cores in Linux or MacOS system! 

I just randomly tried the tutorial with subsampling 3500 genes, the estimated time showing that it will be finished around 4 hours and 37 mins if I use 10 cores. 

![Screen Shot 2022-05-26 at 11 35 04 PM](https://user-images.githubusercontent.com/28901481/170624114-63909749-bd85-42ad-8eef-b9111d82cfa4.png)
