### ISSUE TITLE
How to get SE for LogFC

### ISSUE THREAD

**Issue by kvshams** [xzhoulab/iDEA#4]
Hi, 
This may not be relevant to `iDEA` but its a dependency in the input. How to get the SE for log2FC . Packages like EdgeR gives only logfc and pvalue. Is there any way to calculate or fetch for this purpose?

**Comment by YingMa1993** [comment]
Hi, 

I just noticed this post since the GitHub seems not send us the notification email. 

Here is an example to calculate the SE. 
ie. assume you have the results of res_edgeR which contains the "logfc" and "pvalue" column. 
pvalue <- res_edgeR$pvalue #### the pvalue column
zscore <- qnorm(pvalue/2.0, lower.tail=FALSE) #### convert the pvalue to z-score
# summary statistics 
beta <- res_edgeR$logfc  ## logfc you have 
se_beta <- beta/zscore  ## to approximate the standard error of beta

Best,
Ying

**Comment by zh-Bian** [comment]
Hi,
I noticed that the second column should be the variance of the coefficient for each gene. The variance of the variance seems equal to the sd()/mean(), whether is equal to logfc/zscore?
Because I calculate the variance of coefficient by sd()/mean(), however, it's wrong in the'' idea <- iDEA.louis(idea)'' (Error in { : task 10 failed - "参数长度为零")
![image](https://user-images.githubusercontent.com/54278620/82280337-41ce5300-99c1-11ea-9458-0e781a127ca2.png)
So I think whether is related to the method for the variance of coefficient.

**Comment by zh-Bian** [comment]
Hi,
I noticed that the second column should be the variance of the coefficient for each gene. The variance of the variance seems equal to the sd()/mean(), whether is equal to logfc/zscore?
Because I calculate the variance of coefficient by sd()/mean(), however, it's wrong in the'' idea <- iDEA.louis(idea)'' (Error in { : task 10 failed - "参数长度为零")
![微信截图_20200519111251](https://user-images.githubusercontent.com/54278620/82280571-b99c7d80-99c1-11ea-9eb8-450088d621d9.png)
So I think whether is related to the method for the variance of coefficient.

Best,
Bian

**Comment by zh-Bian** [comment]
Hi,
I noticed that the second column should be the variance of the coefficient for each gene. The variance of the coefficient seems equal to the sd()/mean(), whether is equal to logfc/zscore?
Because I calculate the variance of coefficient by sd()/mean(), however, it's wrong in the'' idea <- iDEA.louis(idea)'' (Error in { : task 10 failed - "参数长度为零")
![微信截图_20200519111251](https://user-images.githubusercontent.com/54278620/82280631-db960000-99c1-11ea-865d-31488165adca.png)

So I think whether is related to the method for the variance of coefficient.

Best,
Bian

**Comment by YingMa1993** [comment]
Hi, Bian,
I don't quite follow your question. Did you mean you calculated the standard error as sd()/mean() and then it generates error? I don't know what the sd()/mean() represents here. The standard deviation and standard error are two different conceptions. Could you please try the example code that we provided?

**Comment by Tushar-87** [comment]
I have a similar question. 
I have p value, n for two independent samples (larger than 100) and ratio of means (log folc change). The test used for significance was Wilcoxon rank sum test. How can I calculate standard deviation for each sample?

**Comment by YingMa1993** [comment]
Hi @Tushar-87 
You can still convert the pvalue to z-score first, and estimate the standard error using log-fc and z-score since for large samples, the test statistics is approximately normally distributed. 
zscore <- qnorm(pvalue/2.0, lower.tail=FALSE) 
se <- log-fc/zscore

**Comment by liu2005678** [comment]
primerid component         contrast Pr(>Chisq)      ci.hi       ci.lo       coef          z
1    7SK.1         C orig.identpc3sal  1.0000000  0.4843993  0.02869869  0.2565490  2.2068296
2    7SK.1         C      (Intercept)         NA  0.2971688  0.03406991  0.1656193  2.4675738
3    7SK.1         D orig.identpc3sal  0.6320606  1.6465945 -2.57702704 -0.4652163 -0.4317655
4    7SK.1         D      (Intercept)         NA -3.9083399 -6.62140841 -5.2648741 -7.6068581
5    7SK.1         H orig.identpc3sal  0.6320606         NA          NA         NA         NA
6    7SK.1         S orig.identpc3sal         NA         NA          NA         NA  1.2551598

The above is  the results results recovered by MAST, there is no "fold change" column. How can I perform iDEA analysis.
please help. 
I have tried a lot. 
The Seurat packages "FindMarkers" do return p value and foldchange, however,  it only return genes that are differentially expressed, which is not  suitable for Volcano plot
