### ISSUE TITLE
python version of iDEA

### ISSUE THREAD

**Issue by Fronttooth** [xzhoulab/iDEA#5]
Dear authors,

Thanks for contributing this wonderful tool. I am wondering if you will develop a python version of it? Thanks

**Comment by YingMa1993** [comment]
Hi, 

I just noticed this post since the GitHub seems not send us the notification email. Thanks for your suggestion. However, currently we don't have the plan to develop the python version. We'll consider it in the future! Do you have any problems with the R-package that we can help you? 

Best,
Ying
